/*
 * ex02_matmul.c — Compile HLO and execute add + matmul on TPU.
 *
 * Requires: HLO files generated by gen_hlo.py.
 *   export TPU_DATA_DIR=<dir containing add.hlo.pb, matmul.hlo.pb, compile_opts.pb>
 *
 * Compile: make ex02_matmul
 * Run:     TPU_DATA_DIR=. ./ex02_matmul
 */

#include "tpu.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

static void make_path(char* buf, size_t bufsz, const char* file)
{
    const char* d = getenv("TPU_DATA_DIR");
    snprintf(buf, bufsz, "%s/%s", d ? d : ".", file);
}

int main(void)
{
    printf("=== ex02: HLO compile + execute on TPU ===\n\n");

    tpu_ctx_t* ctx = tpu_init(NULL);
    if (!ctx) { fprintf(stderr, "tpu_init: %s\n", tpu_strerror(NULL)); return 1; }

    char add_pb[512], mm_pb[512], opts_pb[512];
    make_path(add_pb,  sizeof(add_pb),  "add.hlo.pb");
    make_path(mm_pb,   sizeof(mm_pb),   "matmul.hlo.pb");
    make_path(opts_pb, sizeof(opts_pb), "compile_opts.pb");

    /* ── Test 1: element-wise add (x + x) ──────────────────────────────── */
    printf("--- Test 1: x + x ---\n");
    tpu_exec_t* add_exec = tpu_compile_file(ctx, add_pb, opts_pb);
    if (!add_exec) { fprintf(stderr, "compile add: %s\n", tpu_strerror(ctx)); return 1; }
    printf("Compiled. Outputs per device: %d\n", tpu_exec_num_outputs(add_exec));

    float x[16];
    for (int i = 0; i < 16; i++) x[i] = (float)(i + 1);
    int64_t shape44[] = {4, 4};

    tpu_buf_t* x_buf = tpu_upload_f32(ctx, 0, x, shape44, 2);
    if (!x_buf) { fprintf(stderr, "upload x: %s\n", tpu_strerror(ctx)); return 1; }

    tpu_buf_t* add_out = tpu_run1(add_exec, x_buf);
    if (!add_out) { fprintf(stderr, "run add: %s\n", tpu_strerror(ctx)); return 1; }

    float add_result[16] = {0};
    tpu_download(add_out, add_result, sizeof(add_result));

    int add_ok = 1;
    for (int i = 0; i < 16; i++)
        if (fabsf(add_result[i] - x[i] * 2.f) > 0.001f) add_ok = 0;

    printf("Result (x + x): [");
    for (int i = 0; i < 16; i++) {
        printf("%.0f%s", add_result[i], i < 15 ? "," : "");
        if (i == 7) printf("\n                 ");
    }
    printf("]\nVerify: %s\n\n", add_ok ? "PASSED" : "FAILED");

    tpu_buf_free(add_out);
    tpu_buf_free(x_buf);
    tpu_exec_free(add_exec);

    /* ── Test 2: matrix multiply (A @ B) ────────────────────────────────── */
    printf("--- Test 2: A @ B (identity @ B = B) ---\n");
    tpu_exec_t* mm_exec = tpu_compile_file(ctx, mm_pb, opts_pb);
    if (!mm_exec) { fprintf(stderr, "compile matmul: %s\n", tpu_strerror(ctx)); return 1; }

    /* A = identity 4x4, B = 1..16 */
    float a[16] = {0};
    a[0] = a[5] = a[10] = a[15] = 1.f;
    float b[16];
    for (int i = 0; i < 16; i++) b[i] = (float)(i + 1);

    tpu_buf_t* a_buf = tpu_upload_f32(ctx, 0, a, shape44, 2);
    tpu_buf_t* b_buf = tpu_upload_f32(ctx, 0, b, shape44, 2);

    tpu_buf_t* mm_out = tpu_run2(mm_exec, a_buf, b_buf);
    if (!mm_out) { fprintf(stderr, "run matmul: %s\n", tpu_strerror(ctx)); return 1; }

    float mm_result[16] = {0};
    tpu_download(mm_out, mm_result, sizeof(mm_result));

    int mm_ok = 1;
    for (int i = 0; i < 16; i++)
        if (fabsf(mm_result[i] - b[i]) > 0.001f) mm_ok = 0;

    printf("Result (I @ B = B):\n");
    for (int r = 0; r < 4; r++) {
        printf("  [");
        for (int c = 0; c < 4; c++) printf("%6.1f", mm_result[r*4+c]);
        printf("  ]\n");
    }
    printf("Verify (I @ B == B): %s\n\n", mm_ok ? "PASSED" : "FAILED");

    /* Now B @ B */
    printf("--- Test 3: B @ B ---\n");
    tpu_buf_t* b2_buf = tpu_upload_f32(ctx, 0, b, shape44, 2);
    tpu_buf_t* bb_out = tpu_run2(mm_exec, b_buf, b2_buf);
    if (!bb_out) { fprintf(stderr, "run B@B: %s\n", tpu_strerror(ctx)); return 1; }

    float bb[16] = {0};
    tpu_download(bb_out, bb, sizeof(bb));

    /* CPU reference */
    float ref[16] = {0};
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            for (int k = 0; k < 4; k++)
                ref[i*4+j] += b[i*4+k] * b[k*4+j];

    int bb_ok = 1;
    for (int i = 0; i < 16; i++) if (fabsf(bb[i] - ref[i]) > 0.5f) bb_ok = 0;

    printf("Result (B @ B):\n");
    for (int r = 0; r < 4; r++) {
        printf("  [");
        for (int c = 0; c < 4; c++) printf("%7.0f", bb[r*4+c]);
        printf("  ]\n");
    }
    printf("Verify: %s\n\n", bb_ok ? "PASSED" : "FAILED");

    tpu_buf_free(mm_out);
    tpu_buf_free(bb_out);
    tpu_buf_free(a_buf);
    tpu_buf_free(b_buf);
    tpu_buf_free(b2_buf);
    tpu_exec_free(mm_exec);
    tpu_destroy(ctx);
    return (add_ok && mm_ok && bb_ok) ? 0 : 1;
}
