/*
 * ex03_spmd.c — SPMD: run same kernel across all addressable devices.
 *
 * Each device independently computes x + x on its own input buffer.
 * Requires compile_opts_n4.pb (num_replicas=4), generated by gen_hlo.py.
 * Uses tpu_exec_device_order() to upload each input to the correct device
 * for each replica (XLA's mesh topology may not match 0,1,2,3 order).
 *
 * Requires: add.hlo.pb, compile_opts_n4.pb
 *   export TPU_DATA_DIR=<dir>
 *
 * Compile: make ex03_spmd
 * Run:     TPU_DATA_DIR=. ./ex03_spmd
 */

#include "tpu.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

static void make_path(char* buf, size_t bufsz, const char* f) {
    const char* d = getenv("TPU_DATA_DIR"); if (!d) d = ".";
    snprintf(buf, bufsz, "%s/%s", d, f);
}

int main(void)
{
    printf("=== ex03: SPMD execution across all devices ===\n\n");

    tpu_ctx_t* ctx = tpu_init(NULL);
    if (!ctx) { fprintf(stderr, "tpu_init: %s\n", tpu_strerror(NULL)); return 1; }

    int ndevs = tpu_num_addressable_devices(ctx);
    printf("Running on %d device(s)\n\n", ndevs);

    /* Compile add (x + x) with num_replicas=ndevs */
    char add_pb[512], opts_pb[512];
    make_path(add_pb,  sizeof(add_pb),  "add.hlo.pb");
    make_path(opts_pb, sizeof(opts_pb), "compile_opts_n4.pb");
    tpu_exec_t* exec = tpu_compile_file(ctx, add_pb, opts_pb);
    if (!exec) { fprintf(stderr, "compile: %s\n", tpu_strerror(ctx)); return 1; }

    /* Find which physical device each replica is assigned to */
    int* dev_order = (int*)malloc((size_t)ndevs * sizeof(int));
    if (tpu_exec_device_order(exec, dev_order, (size_t)ndevs)) {
        fprintf(stderr, "device_order: %s\n", tpu_strerror(ctx)); return 1;
    }
    printf("Replica-to-device assignment:\n");
    for (int r = 0; r < ndevs; r++)
        printf("  replica %d → device %d\n", r, dev_order[r]);
    printf("\n");

    /* Upload distinct input to the device assigned to each replica */
    tpu_buf_t** inputs = (tpu_buf_t**)malloc((size_t)ndevs * sizeof(tpu_buf_t*));
    int64_t shape[] = {4, 4};
    for (int r = 0; r < ndevs; r++) {
        float x[16];
        for (int i = 0; i < 16; i++) x[i] = (float)(r * 16 + i + 1);
        inputs[r] = tpu_upload_f32(ctx, dev_order[r], x, shape, 2);
        if (!inputs[r]) { fprintf(stderr, "upload replica %d: %s\n", r, tpu_strerror(ctx)); return 1; }
    }

    /* Build per-replica arg lists */
    tpu_buf_t*** arg_lists = (tpu_buf_t***)malloc((size_t)ndevs * sizeof(tpu_buf_t**));
    for (int r = 0; r < ndevs; r++)
        arg_lists[r] = &inputs[r];

    tpu_buf_t** out_lists = NULL;
    if (tpu_run_spmd(exec,
                     (tpu_buf_t* const* const*)arg_lists,
                     (size_t)ndevs, 1,
                     &out_lists, 1)) {
        fprintf(stderr, "run_spmd: %s\n", tpu_strerror(ctx));
        free(arg_lists); free(dev_order); return 1;
    }
    free(arg_lists);

    /* Verify: each output[r] should equal 2 * input[r] */
    int all_ok = 1;
    for (int r = 0; r < ndevs; r++) {
        tpu_buf_t* out = out_lists[r * 1 + 0];
        float result[16] = {0};
        tpu_download(out, result, sizeof(result));
        int ok = 1;
        for (int i = 0; i < 16; i++) {
            float expected = (float)(2 * (r * 16 + i + 1));
            if (fabsf(result[i] - expected) > 0.001f) ok = 0;
        }
        printf("Replica %d (dev %d): x+x = [%.0f ... %.0f]  %s\n",
               r, dev_order[r], result[0], result[15], ok ? "OK" : "WRONG");
        if (!ok) all_ok = 0;
    }

    printf("\nSPMD: %s\n", all_ok ? "PASSED" : "FAILED");

    tpu_spmd_outputs_free(out_lists, (size_t)ndevs, 1);
    for (int r = 0; r < ndevs; r++) tpu_buf_free(inputs[r]);
    free(inputs); free(dev_order);
    tpu_exec_free(exec);
    tpu_destroy(ctx);
    return all_ok ? 0 : 1;
}
